### ISSUE TITLE
Error while handling API request, no other debugging info

### ISSUE THREAD

**Issue by earwig** [valhallasw/plagiabot#14] opened 2017-11-06 16:57 UTC
URL: https://tools.wmflabs.org/eranbot/plagiabot/api.py?action=suspected_diffs&page_title=User:EarwigBot/Copyvios/Tests/2&lang=en&report=1

Output:

```
Error encountered while handling the request. Please report a bug: https://github.com/valhallasw/plagiabot/issues
[]
```

**Comment by eranroz** [comment] 2017-11-07 22:50
Caused by: https://phabricator.wikimedia.org/T179227 (it used different configuration file)
Fixed on production

**Closed as completed** 2017-11-07 22:53 UTC
